apiVersion: v1
kind: Service
metadata:
  name: {{.Values.applicationName }}-service
  labels:
    app: {{ .Values.applicationName }}-service
  {{ if .Values.loadBalancer.enabled }}
  annotations:
    # Load balancer type: Internal.
    yandex.cloud/load-balancer-type: internal
    # ID of the subnet to allocate an IP address for
    yandex.cloud/subnet-id: e9b9qu7fecovjqohq1e8
  {{ end }}
spec:
  ports:
    - port: {{ .Values.app.yc.server.http.port }} # 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.app.yc.server.grpc.port }} # 9090
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.app.yc.metrics.port }} # 9153
      targetPort: metrics
      protocol: TCP
      name: metrics
  {{ if .Values.loadBalancer.enabled }}
  type: LoadBalancer
  {{ else }}
  type: NodePort
  {{ end }}
  selector:
    app: {{ .Values.applicationName }}