// Code generated by gitlab.lenvendo.ru/product/grade-factor/services/service-generator  REMOVE THIS STRING ON EDIT OR DO NOT EDIT.
package echo

import (
	"context"
	"strconv"
	"time"

	"github.com/go-kit/kit/metrics"

	tool "github.com/arashi5/echo/tools/metrics"
)

// NewMetricService returns an instance of an instrumenting Service.
func NewMetricsService(ctx context.Context, s Service) Service {
	counter, latency := tool.FromContext(ctx)
	return &metricService{counter, latency, s}
}

type metricService struct {
	requestCount   metrics.Counter
	requestLatency metrics.Histogram
	Service
}

func (s *metricService) CreateEcho(ctx context.Context, req *CreateEchoRequest) (resp *CreateEchoResponse, err error) {
	defer func(begin time.Time) {
		go func() {
			s.requestCount.With("service", "echo", "handler", "CreateEcho", "code", strconv.Itoa(getHTTPStatusCode(err))).Add(1)
			s.requestLatency.With("service", "echo", "handler", "CreateEcho", "code", strconv.Itoa(getHTTPStatusCode(err))).Observe(time.Since(begin).Seconds())
		}()
	}(time.Now())
	return s.Service.CreateEcho(ctx, req)
}

func (s *metricService) GetEcho(ctx context.Context, req *GetEchoListRequest) (resp *GetEchoListResponse, err error) {
	defer func(begin time.Time) {
		go func() {
			s.requestCount.With("service", "echo", "handler", "GetEcho", "code", strconv.Itoa(getHTTPStatusCode(err))).Add(1)
			s.requestLatency.With("service", "echo", "handler", "GetEcho", "code", strconv.Itoa(getHTTPStatusCode(err))).Observe(time.Since(begin).Seconds())
		}()
	}(time.Now())
	return s.Service.GetEcho(ctx, req)
}
