// Code generated by gitlab.lenvendo.ru/product/grade-factor/services/service-generator  REMOVE THIS STRING ON EDIT OR DO NOT EDIT.
package echo

import (
	"context"
	"encoding/json"

	kitnats "github.com/go-kit/kit/transport/nats"
	"github.com/nats-io/nats.go"
)

func NewNatsPublisher(ctx context.Context, nc *nats.Conn) Service {
	return endpoints{
		CreateEchoEndpoint: kitnats.NewPublisher(
			nc,
			"experimental-echo-service-echo-createEcho",
			kitnats.EncodeJSONRequest,
			decodeHTTPCreateEcho,
		).Endpoint(),
		GetEchoEndpoint: kitnats.NewPublisher(
			nc,
			"experimental-echo-service-echo-getEcho",
			kitnats.EncodeJSONRequest,
			decodeHTTPGetEcho,
		).Endpoint(),
	}
}

func decodeHTTPCreateEcho(_ context.Context, msg *nats.Msg) (interface{}, error) {
	var response CreateEchoResponse
	if err := json.Unmarshal(msg.Data, &response); err != nil {
		return nil, err
	}
	return response, nil
}

func decodeHTTPGetEcho(_ context.Context, msg *nats.Msg) (interface{}, error) {
	var response GetEchoListResponse
	if err := json.Unmarshal(msg.Data, &response); err != nil {
		return nil, err
	}
	return response, nil
}
