// Code generated by gitlab.lenvendo.ru/product/grade-factor/services/service-generator  REMOVE THIS STRING ON EDIT OR DO NOT EDIT.
package echo

import (
	"context"
	"encoding/json"

	"github.com/go-kit/kit/log"
	kitnats "github.com/go-kit/kit/transport/nats"
	"github.com/nats-io/nats.go"
	"github.com/arashi5/echo/tools/logging"
)

func NewNatsSubscriber(ctx context.Context, nc *nats.Conn, svc Service) error {
	logger := logging.FromContext(ctx)
	logger = log.With(logger, "nats handler")
	{
		ra := kitnats.NewSubscriber(
			makeCreateEchoEndpoint(svc),
			decodeNATSCreateEchoRequestRequest,
			kitnats.EncodeJSONResponse,
			kitnats.SubscriberErrorLogger(logger),
		)
		if _, err := nc.QueueSubscribe("experimental-echo-service-echo-createEcho", "echo", ra.ServeMsg(nc)); err != nil {
			return err
		}
	}
	{
		ra := kitnats.NewSubscriber(
			makeGetEchoEndpoint(svc),
			decodeNATSGetEchoListRequestRequest,
			kitnats.EncodeJSONResponse,
			kitnats.SubscriberErrorLogger(logger),
		)
		if _, err := nc.QueueSubscribe("experimental-echo-service-echo-getEcho", "echo", ra.ServeMsg(nc)); err != nil {
			return err
		}
	}

	return nil
}

func decodeNATSCreateEchoRequestRequest(_ context.Context, msg *nats.Msg) (interface{}, error) {
	var request CreateEchoRequest
	if err := json.Unmarshal(msg.Data, &request); err != nil {
		return nil, err
	}
	return request, nil
}

func decodeNATSGetEchoListRequestRequest(_ context.Context, msg *nats.Msg) (interface{}, error) {
	var request GetEchoListRequest
	if err := json.Unmarshal(msg.Data, &request); err != nil {
		return nil, err
	}
	return request, nil
}
