stage: 'dev'
ingress: true
applicationName: experimental-echo-service
replicaCount: 1
pullPolicy: IfNotPresent
loadBalancer:
  enabled: false
gitLabSecret:
  enabled: true
tlsSecret:
  enabled: false
service:
  enabled: true
  type: ClusterIP
  ports:
    http: 80
    grpc: 8081
app:
  yc:
    domain: stage.example.com
    image:
      repository: registry.github.com
      tag: "latest"
    server:
      http:
        port: 8080
        timeoutSec: 86400
      grpc:
        port: 9090
        timeoutSec: 86400
    grpc:
      tls:
        enabled: false
    logger:
      level: debug
      timeFormat: 2006-01-02T15:04:05.999999999
    metrics:
      enabled: true
      port: 9153
    limiter:
      enabled: false
      limit: "10000.0"
    redis:
      port: 6379
    postgresql:
      host: localhost
      port: 5432
      user: postgres
      password: postgres
      databaseName: echo
      secure: disable
      schema: echo
